/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ApiPublicPixWebhookRouteImport } from './routes/api/public/pix/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixWebhookRoute = ApiPublicPixWebhookRouteImport.update({
  id: '/api/public/pix/webhook',
  path: '/api/public/pix/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/quiz': typeof QuizRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/quiz': typeof QuizRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oferta': typeof OfertaRoute
  '/pagamento': typeof PagamentoRoute
  '/quiz': typeof QuizRoute
  '/api/public/pix/webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/oferta' | '/pagamento' | '/quiz' | '/api/public/pix/webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oferta' | '/pagamento' | '/quiz' | '/api/public/pix/webhook'
  id:
    | '__root__'
    | '/'
    | '/oferta'
    | '/pagamento'
    | '/quiz'
    | '/api/public/pix/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfertaRoute: typeof OfertaRoute
  PagamentoRoute: typeof PagamentoRoute
  QuizRoute: typeof QuizRoute
  ApiPublicPixWebhookRoute: typeof ApiPublicPixWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/webhook': {
      id: '/api/public/pix/webhook'
      path: '/api/public/pix/webhook'
      fullPath: '/api/public/pix/webhook'
      preLoaderRoute: typeof ApiPublicPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfertaRoute: OfertaRoute,
  PagamentoRoute: PagamentoRoute,
  QuizRoute: QuizRoute,
  ApiPublicPixWebhookRoute: ApiPublicPixWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
